"""Create

Revision ID: 6f9920cc5dd7
Revises: 
Create Date: 2021-08-24 01:28:35.038127

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6f9920cc5dd7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resellers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("cpf", sa.String(length=14), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
    )
    op.create_table(
        "purchases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=15), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("cashback_percent", sa.Numeric(), nullable=False),
        sa.Column("cashback_amount", sa.Numeric(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IN_VALIDATION", "APPROVED", "DENIED", name="status"),
            nullable=False,
        ),
        sa.Column("reseller_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reseller_id"],
            ["resellers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("purchases")
    op.drop_table("resellers")
    # ### end Alembic commands ###
